services:
    Edgar\EzUIBookmark\Component\TwigComponent:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        arguments:
            $template: 'EdgarEzUIBookmarkBundle:bookmark/component:scripts.html.twig'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'script-body' }