services:
    Edgar\EzUIBookmark\Component\FooterTwigComponent:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        arguments:
            $template: 'EdgarEzUIBookmarkBundle:bookmark/component:bookmark_footer.html.twig'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'script-body' }

    Edgar\EzUIBookmark\Component\HeadTwigComponent:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        arguments:
            $template: 'EdgarEzUIBookmarkBundle:bookmark/component:bookmark_head.html.twig'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }
