imports:
    - { resource: controllers.yml }
    - { resource: dashboard.yml }
    - { resource: components.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIBookmarkBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.content_sidebar_right, method: onMenuConfigure }

    Edgar\EzUIBookmarkBundle\Templating\Twig\BookmarkExtension:
        tags:
            - { name: twig.extension }

    Edgar\EzUIBookmarkBundle\EventListener\ProfileConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: edgar_ezuiprofile.menu_configure.profile_sidebar_left, method: onMenuConfigure }

    Edgar\EzUIBookmarkBundle\SignalSlot\Slot\DeleteLocationSlot:
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\DeleteLocationSignal }
