imports:
    - { resource: controllers.yml }
    - { resource: dashboard.yml }
    - { resource: components.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIBookmarkBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.content_sidebar_right, method: onMenuConfigure }

